services:
  - type: web
    name: received-images-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: YOLO_CONFIG_DIR
        value: /tmp
